import os
import math
import shutil
import subprocess
from PIL import Image, ImageDraw, ImageFilter, ImageEnhance

BASE_DIR = r'C:\Users\admin\Music\chufang'
ARTIFACT_DIR = r'C:\Users\admin\.gemini\antigravity\brain\a581706c-feba-4a01-94fc-8c62ff40a9bf'
CAT_ASSET_DIR = os.path.join(BASE_DIR, 'packages', 'web-greybox', 'public', 'assets', 'cat')
TEMP_FRAMES_DIR = os.path.join(BASE_DIR, 'scripts', 'temp_frames')

os.makedirs(CAT_ASSET_DIR, exist_ok=True)
os.makedirs(TEMP_FRAMES_DIR, exist_ok=True)

# Master images generated by Imagen
IMG_MASTER = Image.open(os.path.join(CAT_ASSET_DIR, 'restaurant_stage_master.jpg')).convert('RGBA')
IMG_TIE = Image.open(os.path.join(ARTIFACT_DIR, 'cat_open_tie_1790351451552.jpg')).convert('RGBA')
IMG_CHEER = Image.open(os.path.join(ARTIFACT_DIR, 'cat_open_cheer_1790351379389.jpg')).convert('RGBA')
IMG_CHOP = Image.open(os.path.join(ARTIFACT_DIR, 'cat_work_chop_1790351539446.jpg')).convert('RGBA')
IMG_STIR = Image.open(os.path.join(ARTIFACT_DIR, 'cat_work_stir_1790351635057.jpg')).convert('RGBA')
IMG_PASS = Image.open(os.path.join(ARTIFACT_DIR, 'cat_work_pass_1790351734241.jpg')).convert('RGBA')
IMG_DANCE = Image.open(os.path.join(ARTIFACT_DIR, 'cat_win_dance_1790351847125.jpg')).convert('RGBA')
IMG_SWAY = Image.open(os.path.join(ARTIFACT_DIR, 'cat_win_sway_1790351968371.jpg')).convert('RGBA')

# Target video resolution: 432 x 774 (aspect ratio 9:16 approx, crisp & lightweight)
W, H = 432, 774

def resize_to_target(im):
    return im.resize((W, H), Image.Resampling.LANCZOS)

IMG_MASTER = resize_to_target(IMG_MASTER)
IMG_TIE = resize_to_target(IMG_TIE)
IMG_CHEER = resize_to_target(IMG_CHEER)
IMG_CHOP = resize_to_target(IMG_CHOP)
IMG_STIR = resize_to_target(IMG_STIR)
IMG_PASS = resize_to_target(IMG_PASS)
IMG_DANCE = resize_to_target(IMG_DANCE)
IMG_SWAY = resize_to_target(IMG_SWAY)

def blend(im1, im2, alpha):
    """Smoothly blends im1 into im2 by alpha in [0, 1]"""
    alpha = max(0.0, min(1.0, alpha))
    return Image.blend(im1, im2, alpha)

def draw_steam_particle(draw, x, y, radius, opacity):
    color = (255, 255, 255, int(opacity * 255))
    draw.ellipse([x - radius, y - radius, x + radius, y + radius], fill=color)

def draw_star_sparkle(draw, x, y, size, opacity):
    c = (255, 230, 110, int(opacity * 255))
    draw.line([x - size, y, x + size, y], fill=c, width=2)
    draw.line([x, y - size, x, y + size], fill=c, width=2)
    draw.line([x - size*0.5, y - size*0.5, x + size*0.5, y + size*0.5], fill=c, width=1)
    draw.line([x - size*0.5, y + size*0.5, x + size*0.5, y - size*0.5], fill=c, width=1)

def draw_golden_coin(draw, x, y, radius, tilt=0):
    # Oval for tilted 3D coin
    ry = radius * math.cos(tilt)
    rx = radius
    fill_gold = (245, 185, 45, 245)
    border_gold = (210, 140, 20, 255)
    inner_gold = (255, 220, 90, 245)
    bbox = [x - rx, y - abs(ry), x + rx, y + abs(ry)]
    draw.ellipse(bbox, fill=fill_gold, outline=border_gold, width=2)
    if abs(ry) > 4:
        inner_bbox = [x - rx*0.6, y - abs(ry)*0.6, x + rx*0.6, y + abs(ry)*0.6]
        draw.ellipse(inner_bbox, outline=inner_gold, width=1)

def encode_video(frames_pattern, output_prefix, fps):
    webm_out = os.path.join(CAT_ASSET_DIR, f'{output_prefix}.webm')
    mp4_out = os.path.join(CAT_ASSET_DIR, f'{output_prefix}.mp4')
    
    # 1. MP4 (H.264)
    cmd_mp4 = [
        'ffmpeg', '-y', '-framerate', str(fps),
        '-i', frames_pattern,
        '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
        '-crf', '19', '-preset', 'medium',
        mp4_out
    ]
    subprocess.run(cmd_mp4, check=True)
    
    # 2. WebM (VP9)
    cmd_webm = [
        'ffmpeg', '-y', '-framerate', str(fps),
        '-i', frames_pattern,
        '-c:v', 'libvpx-vp9', '-pix_fmt', 'yuv420p',
        '-crf', '26', '-b:v', '0',
        webm_out
    ]
    subprocess.run(cmd_webm, check=True)

    # Copy to artifact directory
    shutil.copy(webm_out, os.path.join(ARTIFACT_DIR, f'{output_prefix}.webm'))
    shutil.copy(mp4_out, os.path.join(ARTIFACT_DIR, f'{output_prefix}.mp4'))
    print(f'[OK] Encoded {output_prefix}: MP4 & WebM saved successfully.')

# =========================================================================
# 1. BUILD CAT_OPEN (2.6s, 26 frames @ 10fps)
# =========================================================================
def build_cat_open():
    print('Building CAT_OPEN frames...')
    out_dir = os.path.join(TEMP_FRAMES_DIR, 'cat_open')
    os.makedirs(out_dir, exist_ok=True)

    total_frames = 26
    for i in range(total_frames):
        t = i / 10.0 # seconds
        frame = Image.new('RGBA', (W, H))

        if t < 0.4:
            # 0.0s ~ 0.4s: Cloud puff emergence on counter
            frame.paste(IMG_MASTER, (0, 0))
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            progress = t / 0.4
            puff_radius = 20 + progress * 50
            puff_opacity = 0.85 * (1.0 - progress * 0.4)
            # Cloud puffs around cat center (x=216, y=360)
            for ox, oy, r in [(-30, 20, 35), (30, 15, 30), (0, -10, 45), (-15, -30, 25), (20, -25, 25)]:
                draw_steam_particle(draw, 216 + ox * progress, 360 + oy * progress, (puff_radius * 0.7 + r) * 0.5, puff_opacity)
            overlay = overlay.filter(ImageFilter.GaussianBlur(radius=6))
            frame = Image.alpha_composite(frame, overlay)

        elif t < 1.4:
            # 0.4s ~ 1.4s: Cat emerges & ties red headband
            progress = (t - 0.4) / 1.0
            frame = blend(IMG_MASTER, IMG_TIE, progress)
            # Subtle cloth flutter at headband ribbon (top right of cat head)
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            flutter = math.sin(progress * math.pi * 4) * 3
            draw.line([290, 240, 305 + flutter, 245], fill=(215, 55, 45, 200), width=3)
            frame = Image.alpha_composite(frame, overlay)

        elif t < 2.1:
            # 1.4s ~ 2.1s: Cat powers up into fighting cheer pose ('ganbatte!')
            progress = (t - 1.4) / 0.7
            frame = blend(IMG_TIE, IMG_CHEER, progress)
            # Golden sparkle stars
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            for sx, sy, size, phase in [(130, 260, 8, 0), (310, 250, 10, 0.5), (216, 210, 12, 0.2), (150, 320, 6, 0.8), (290, 310, 7, 0.3)]:
                op = 0.5 + 0.5 * math.sin((progress * 2 + phase) * math.pi * 2)
                draw_star_sparkle(draw, sx, sy, size, op)
            frame = Image.alpha_composite(frame, overlay)

        else:
            # 2.1s ~ 2.6s: Cat turns to counter, ready to chop
            progress = (t - 2.1) / 0.5
            frame = blend(IMG_CHEER, IMG_CHOP, progress)

        frame.convert('RGB').save(os.path.join(out_dir, f'frame_{i:03d}.png'))

    encode_video(os.path.join(out_dir, 'frame_%03d.png'), 'restaurant_open', 10)

# =========================================================================
# 2. BUILD CAT_WORK_LOOP (7.2s, 72 frames @ 10fps, STRICT SEAMLESS LOOP)
# =========================================================================
def build_cat_work_loop():
    print('Building CAT_WORK_LOOP frames (seamless)...')
    out_dir = os.path.join(TEMP_FRAMES_DIR, 'cat_work_loop')
    os.makedirs(out_dir, exist_ok=True)

    total_frames = 72
    for i in range(total_frames):
        t = i / 10.0 # 0.0s to 7.1s
        frame = Image.new('RGBA', (W, H))

        if t < 1.6:
            # 0.0s ~ 1.6s: Chopping vegetables (knife bobbing, scallion cuts)
            frame.paste(IMG_CHOP, (0, 0))
            chop_cycle = math.sin(t * math.pi * 6) # 3 chops/sec
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            # Subtle knife cut line
            knife_y = 390 + max(0, chop_cycle * 4)
            draw.line([190, knife_y, 220, knife_y + 12], fill=(240, 240, 240, 120), width=2)
            frame = Image.alpha_composite(frame, overlay)

        elif t < 2.5:
            # 1.6s ~ 2.5s: Cat pauses, looks up at printer as ticket feeds out
            progress = (t - 1.6) / 0.9
            frame = blend(IMG_CHOP, IMG_MASTER, progress)
            # Animated ticket feeding out of printer (top right, x=310, y=80)
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            feed_len = progress * 16
            draw.rectangle([305, 125, 355, 135 + feed_len], fill=(255, 253, 247, 240), outline=(210, 195, 175, 200))
            draw.line([310, 130 + feed_len*0.4, 345, 130 + feed_len*0.4], fill=(160, 150, 140, 180), width=1)
            frame = Image.alpha_composite(frame, overlay)

        elif t < 3.4:
            # 2.5s ~ 3.4s: Cat reaches toward pot, transitions to stirring
            progress = (t - 2.5) / 0.9
            frame = blend(IMG_MASTER, IMG_STIR, progress)

        elif t < 5.0:
            # 3.4s ~ 5.0s: Stirring soup in pot, steam puffs rise, ear twitch
            frame.paste(IMG_STIR, (0, 0))
            stir_t = (t - 3.4)
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            # Ladle stirring circle offset
            ladle_ox = math.cos(stir_t * math.pi * 3) * 5
            ladle_oy = math.sin(stir_t * math.pi * 3) * 3
            # Steam particles rising from pot (pot at x=280, y=410)
            for p_idx in range(4):
                age = (stir_t * 1.5 + p_idx * 0.25) % 1.0
                sy = 390 - age * 70
                sx = 280 + math.sin(age * math.pi * 2 + p_idx) * 15
                sr = 12 + age * 16
                sop = (1.0 - age) * 0.65
                draw_steam_particle(draw, sx, sy, sr, sop)
            # Ear twitch at 4.2s
            if 4.0 <= t <= 4.5:
                twitch = math.sin((t - 4.0) * math.pi * 4) * 3
                draw.polygon([(260 + twitch, 205), (280 + twitch, 200), (270 + twitch, 190)], fill=(250, 220, 190, 140))
            overlay = overlay.filter(ImageFilter.GaussianBlur(radius=2))
            frame = Image.alpha_composite(frame, overlay)

        elif t < 6.2:
            # 5.0s ~ 6.2s: Pick up plate & slide toward hatch
            progress = (t - 5.0) / 1.2
            frame = blend(IMG_STIR, IMG_PASS, progress)
            # Plate sliding motion lines
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            slide_x = progress * 15
            draw.line([160 - slide_x, 420, 200 - slide_x, 420], fill=(255, 255, 255, int(150 * (1 - progress))), width=2)
            frame = Image.alpha_composite(frame, overlay)

        else:
            # 6.2s ~ 7.2s: Plate exits hatch, cat smoothly returns to 0.0s chopping pose (PERFECT SEAMLESS WRAP)
            progress = (t - 6.2) / 1.0
            frame = blend(IMG_PASS, IMG_CHOP, progress)

        frame.convert('RGB').save(os.path.join(out_dir, f'frame_{i:03d}.png'))

    encode_video(os.path.join(out_dir, 'frame_%03d.png'), 'restaurant_work_loop', 10)

# =========================================================================
# 3. BUILD CAT_WIN (4.0s, 40 frames @ 10fps with coin rain & meme dance)
# =========================================================================
def build_cat_win():
    print('Building CAT_WIN frames (meme dance & coin rain)...')
    out_dir = os.path.join(TEMP_FRAMES_DIR, 'cat_win')
    os.makedirs(out_dir, exist_ok=True)

    total_frames = 40
    # Pre-generate 14 coins with distinct initial positions, speeds, and tilt rates
    coins = [
        {'x': 180 + (idx * 27) % 180, 'speed': 160 + (idx * 33) % 120, 'delay': idx * 0.1, 'tilt_spd': 4 + idx}
        for idx in range(14)
    ]

    for i in range(total_frames):
        t = i / 10.0 # 0.0s to 3.9s
        frame = Image.new('RGBA', (W, H))

        if t < 0.6:
            # 0.0s ~ 0.6s: Cat pauses, surprised turn towards camera
            progress = t / 0.6
            frame = blend(IMG_CHOP, IMG_MASTER, progress)

        elif t < 1.4:
            # 0.6s ~ 1.4s: Realization & joyful hop into cheer
            progress = (t - 0.6) / 0.8
            hop_y = -math.sin(progress * math.pi) * 8
            base = blend(IMG_MASTER, IMG_CHEER, progress)
            frame.paste(base, (0, int(hop_y)))

        elif t < 2.6:
            # 1.4s ~ 2.6s: Meme Dance Phase 1: Paw covers nose/mouth, fanning air outward
            progress = (t - 1.4) / 1.2
            sway_angle = math.sin(progress * math.pi * 3) * 1.5
            frame = blend(IMG_CHEER, IMG_DANCE, min(1.0, progress * 2))

        elif t < 3.4:
            # 2.6s ~ 3.4s: Meme Dance Phase 2: Sway to other side, alternate paws
            progress = (t - 2.6) / 0.8
            frame = blend(IMG_DANCE, IMG_SWAY, progress)

        else:
            # 3.4s ~ 4.0s: Final Victory Pose with big beaming smile
            progress = (t - 3.4) / 0.6
            frame = blend(IMG_SWAY, IMG_CHEER, progress)

        # Overlay: Local Restaurant Stage Golden Coin Rain (8~16 coins)
        if t >= 0.8:
            coin_t = t - 0.8
            overlay = Image.new('RGBA', (W, H), (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)
            for c in coins:
                if coin_t > c['delay']:
                    c_time = coin_t - c['delay']
                    cy = 60 + c_time * c['speed']
                    cx = c['x'] + math.sin(c_time * 3) * 8
                    if cy < 700:
                        tilt = c_time * c['tilt_spd']
                        draw_golden_coin(draw, cx, cy, radius=11, tilt=tilt)
                        if (i + int(c['x'])) % 3 == 0:
                            draw_star_sparkle(draw, cx + 8, cy - 8, size=6, opacity=0.8)
            frame = Image.alpha_composite(frame, overlay)

        frame.convert('RGB').save(os.path.join(out_dir, f'frame_{i:03d}.png'))

    encode_video(os.path.join(out_dir, 'frame_%03d.png'), 'restaurant_win', 10)

if __name__ == '__main__':
    build_cat_open()
    build_cat_work_loop()
    build_cat_win()
    print('All 3 videos generated successfully!')
